### ISSUE TITLE
Rogue ffmpeg processes

### ISSUE THREAD

**Issue by MarcusSattler** [MediaBrowser/Emby#1408]
It's possible to kick off multiple rogue ffmpeg processes by clicking the play button in the browser multiple times.  You can also do the same in the Roku client by pressing play over and over.  This leaves all of the ffmpeg processes running, can bring the server down to a crawl, and it is hard to tell which ffmpeg process is legit, and which one is rogue since there is no pid to user association.

**Comment by MarcusSattler** [comment]
So this is fixed in the latest beta/dev release?

**Comment by nfnty** [comment]
I'm still having this issue with version `3.0.6030.0`. Seems to only happen with Android devices.

**Comment by LukePulverenti** [comment]
This has been resolved for the next server release, thanks.
