### ISSUE TITLE
Server Dashboard omits the Show Title when client is a FireTV device

### ISSUE THREAD

**Issue by Lord-Malgus** [MediaBrowser/Emby#2840]
Emby dashboard "Active Devices" placard and "Recent Activity" list are omitting the Show name when played from a FireTV device, however other devices (Roku, Browsers, Android TV) are working fine.

Example:
Server Dashboard showing correctly when played from Android Phone App:
    Fred has started playing The Guest Book - Story Four   <<<<<
    8/23/2017, 9:44:20 pm
    App: Emby for Android Mobile, Device: Moto G 4

Incomplete (Missing show title) when played from a FireTV Device (tested under 1.4.44a and 1.4.36a).
   Fred has started playing Story Four     <<<<<
   8/23/2017, 9:45:46 pm
   App: AndroidTv, Device: Amazon AFTS

Further Examples:
Correct when played over Roku client:
   Janet has started playing Psych - 9 Lives  <<<<<
   8/23/2017, 8:33:43 pm
   App: Roku SG, Device: Janet

Correct when played over Chrome browser:
   Mary has started playing Episodes - Episode One   <<<<<
   8/23/2017, 9:35:25 pm
   App: Emby Mobile, Device: Chrome

Incomplete when played on FireTV:
   Sean has started playing Episode One   <<<<<
   8/23/2017, 6:24:42 pm
   App: AndroidTv, Device: Amazon AFTS

As mentioned above, the 'Active Devices' Placard has the same issue, as well as the Background image does not show when client is FireTV..

**Comment by SvenVandenbrande** [comment]
Do you also have a log file, so we can check some stuff...

**Comment by Lord-Malgus** [comment]
[server-63640669405.txt](https://github.com/MediaBrowser/Emby/files/1291009/server-63640669405.txt)

**Comment by Lord-Malgus** [comment]
[server-63640669405.txt](https://github.com/MediaBrowser/Emby/files/1291011/server-63640669405.txt)

**Comment by LukePulverenti** [comment]
This is resolved for the next release of the app, thanks.

**Comment by Lord-Malgus** [comment]
As of version 1.4.57a (FireTV), this is still broken.  Any idea what version it will pop?

**Comment by Lord-Malgus** [comment]
Confirmed this is fixed in v1.4.58a of the FireTV.   Thank you.
