### ISSUE TITLE
Active Devices Dashboard Issue

### ISSUE THREAD

**Issue by hooray4me** [MediaBrowser/Emby#2991]
Amazon Fire stick/tv active devices do not show the Title, episode or a thumbnail. Screenshot shows the same episode from Chrome and an Amazon FireTV. On the latest server version.
![image](https://user-images.githubusercontent.com/12399138/32201243-d92f4a30-bda3-11e7-8d01-51c0e6a91218.png)

**Comment by LukePulverenti** [comment]
This is resolved for the next release of the app, thanks.

**Comment by hooray4me** [comment]
Still not working on .36 
![image](https://user-images.githubusercontent.com/12399138/32354057-0a2e794a-bff6-11e7-8853-7c5c95eefd40.png)

**Comment by LukePulverenti** [comment]
Again, this is resolved in an upcoming update to the fire tv app. It is not server related. Thanks.

**Comment by hooray4me** [comment]
My bad, I didn’t recall seeing that the coming update was for the Fire TV App in your last response… makes sense thanks!
