### ISSUE TITLE
Missing dependencies in docker

### ISSUE THREAD

**Issue by Xiaoming94** [MediaBrowser/Emby#3191]
Looks like some transcoding libs are missing from the container

Problem arises when trying to transcode .ass subtitles. 

see attached log:
[emby.log](https://github.com/MediaBrowser/Emby/files/1783944/emby.log)

Is there a way to fix this?

**Comment by LukePulverenti** [comment]
Hi, this is resolved for the next release. It should already be in the beta. Thanks.

**Comment by Xiaoming94** [comment]
Ok, Nice! Closing this now than 

Kudos for the good work :+1:

**Comment by Xiaoming94** [comment]
Looks like the problems persist on the beta Tag too.
See logs [here](https://pastebin.com/8UjvgLYD)

**Comment by Xiaoming94** [comment]
btw, Keep up the good work! :+1: 

Always nice to have a working alternative to plex :smiley:

**Comment by Xiaoming94** [comment]
After having peeked in the dockerfile, looks like simply adding libavcodec-extra to the `apt-get install` line in the Dockerfile will solve the issue.

**Comment by alucryd** [comment]
You're not looking at the right Dockerfile, we're not using any Debian-based distros as our base image.

I've added iconv support to our ffmpeg build, could you please give the latest beta docker image a try?

**Comment by Xiaoming94** [comment]
Looks like it is resolved now! Thanks! :slightly_smiling_face:
