### ISSUE TITLE
Transcoding fails when attempting to download or sync with conversion

### ISSUE THREAD

**Issue by hllau** [MediaBrowser/Emby#3524]
It works fine when I open the video directly in the app or the web, but fails when trying to download.

Here is the complete log of that doesn't work (when using download or sync feature):
```
2019-02-10 09:00:46.130
Application version: 4.1.0.7

{"Protocol":"File","Id":"80b1d3358e59a7d6c6b5223f660aea57","Path":"/mnt/shared-archives/memories/hllau/Birthday - Dad - 54th/DSCF0243.AVI","Type":"Default","Container":"avi","Size":2809206,"Name":"DSCF0243","IsRemote":false,"RunTimeTicks":50000000,"ReadAtNativeFramerate":false,"DiscardCorruptPts":false,"FillWallClockDts":false,"IgnoreDts":false,"IgnoreIndex":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"Codec":"mjpeg","CodecTag":"MJPG","ColorSpace":"bt470bg","TimeBase":"33333/1000000","CodecTimeBase":"33333/1000000","Title":"FUJIFILM AVI STREAM 0100","VideoRange":"SDR","DisplayTitle":"SD MJPEG","IsInterlaced":false,"BitRate":4416956,"BitDepth":8,"RefFrames":1,"IsDefault":false,"IsForced":false,"Height":240,"Width":320,"AverageFrameRate":30.0003,"RealFrameRate":30.0003,"Profile":"192","Type":"Video","AspectRatio":"4:3","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuvj422p","Level":-99,"IsAnamorphic":false},{"Codec":"pcm_u8","TimeBase":"1/11024","CodecTimeBase":"1/11024","DisplayTitle":"PCM_U8 1 ch","IsInterlaced":false,"BitRate":88192,"BitDepth":8,"Channels":1,"SampleRate":11024,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"Formats":[],"Bitrate":4494774,"RequiredHttpHeaders":{}}

Affected codecs:
>>>>>>  libx264 Software Encoder
        Color Formats: YUV420P, YUVJ420P, YUV422P, YUVJ422P, YUV444P, YUVJ444P, NV12, NV16, NV21, YUV420P10LE, YUV422P10LE, YUV444P10LE, NV20LE
        Profiles: Baseline Profile (Level 6.2), Main Profile (Level 6.2), High Profile (Level 6.2), High 10 Profile (Level 6.2), High 4:2:2 Profile (Level 6.2), High 4:4:4 Profile (Level 6.2)


>>>>>>  FindVideoDecoder - MediaType: mjpeg, Mode: 1
Info    FindVideoDecoder - Checking: 'Automatic software decoder' (Priority: 0)
Info    FindVideoDecoder - Check successful - selecting 'Automatic software decoder'

>>>>>>  FindVideoEncoder - Media: h264, UseHardwareCodecs: True, Mode: 1
Info    FindVideoEncoder - Checking: 'libx264 Software Encoder' (Priority: 0)
Info    Encoder supports input stream
Info    FindVideoEncoder - Check successful - selecting 'libx264 Software Encoder'

/bin/ffmpeg -probesize 1000000  -f avi -codec:0 mjpeg -codec:1 pcm_u8 -i file:"/mnt/shared-archives/memories/hllau/Birthday - Dad - 54th/DSCF0243.AVI" -map 0:0 -map 0:1 -map -0:s -c:v:0 libx264 -force_key_frames "expr:gte(t,n_forced*5)" -pix_fmt yuv420p  -maxrate 3911808 -bufsize 7823616 -preset veryfast -profile high -level 4.1 -crf 23 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 aac -disposition:a:0 default -ac:a:0 1 -ab:a:0 88192 -ar:a:0 11024  -y "/config/sync/17/17/e13c12ff-8de3-4fb6-b5db-f43870904172.mkv"

ffmpeg version 4.0.2-emby_2018_12_09 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (crosstool-NG crosstool-ng-1.23.0)
  configuration: --cc=x86_64-pc-linux-gnu-gcc --arch=x86_64 --prefix=/home/embybuilder/Buildbot/x64/ffmpeg-x64/staging --pkg-config=pkg-config --disable-doc --disable-ffplay --disable-vdpau --disable-xlib --enable-fontconfig --enable-gnutls --enable-gpl --enable-iconv --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libzvbi --enable-version3 --enable-libsmbclient --enable-cuda --enable-cuvid --enable-libmfx --enable-nvenc --enable-vaapi --enable-cross-compile --cross-prefix=x86_64-pc-linux-gnu- --extra-libs='-lexpat -lfreetype -lfribidi -lfontconfig -liconv -lpng -lz -lvorbis -logg -lnettle -lhogweed -lgmp -laddns-samba4 -lasn1util-samba4 -lauthkrb5-samba4 -lCHARSET3-samba4 -lcliauth-samba4 -lcli-cldap-samba4 -lcli-ldap-common-samba4 -lcli-nbt-samba4 -lcli-smb-common-samba4 -lcom_err -lcommon-auth-samba4 -ldbwrap-samba4 -ldcerpc-binding -ldcerpc-samba-samba4 -ldl -lflag-mapping-samba4 -lgenrand-samba4 -lgensec-samba4 -lgse-samba4 -lgssapi_krb5 -llibcli-lsa3-samba4 -llibsmb-samba4 -linterfaces-samba4 -liov-buf-samba4 -lk5crypto -lkrb5 -lkrb5samba-samba4 -lkrb5support -lldb -lldbsamba-samba4 -lmessages-dgm-samba4 -lmessages-util-samba4 -lmsghdr-samba4 -lmsrpc3-samba4 -lndr -lndr-krb5pac -lndr-nbt -lndr-samba-samba4 -lndr-standard -lreplace-samba4 -lsamba-cluster-support-samba4 -lsamba-credentials -lsamba-debug-samba4 -lsamba-errors -lsamba-hostconfig -lsamba-modules-samba4 -lsamba-security-samba4 -lsamba-sockets-samba4 -lsamba-util -lsamba3-util-samba4 -lsamdb -lsamdb-common-samba4 -lsecrets3-samba4 -lserver-id-db-samba4 -lserver-role-samba4 -lsmbconf -lsmbd-shim-samba4 -lsmb-transport-samba4 -lsocket-blocking-samba4 -lsys-rw-samba4 -ltalloc -ltalloc-report-samba4 -ltdb -ltdb-wrap-samba4 -ltevent -ltevent-util -ltime-basic-samba4 -lutil-cmdline-samba4 -lutil-reg-samba4 -lutil-setid-samba4 -lutil-tdb-samba4 -luuid -lwbclient -lwinbind-client-samba4 -ldrm' --target-os=linux --enable-shared --disable-static
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, avi, from 'file:/mnt/shared-archives/memories/hllau/Birthday - Dad - 54th/DSCF0243.AVI':
  Duration: 00:00:05.00, start: 0.000000, bitrate: 4494 kb/s
    Stream #0:0: Video: mjpeg (MJPG / 0x47504A4D), yuvj422p(pc, bt470bg/unknown/unknown), 320x240, 4416 kb/s, 30 fps, 30 tbr, 30 tbn, 30 tbc
    Metadata:
      Make            : FUJIFILM
      Model           : FinePix J25
      DateTime        : 2009:09:20 20:33:43
      JPEGInterchangeFormat:     506
      JPEGInterchangeFormatLength:    5810
      Copyright       :     
      DateTimeOriginal: 2009:09:20 20:33:43
      DateTimeDigitized: 2009:09:20 20:33:43
      MakerNote       : 
                      :  70,  85,  74,  73,  70,  73,  76,  77,  12,   0,   0,   0,  15,   0,   0,   0
                      :   7,   0,   4,   0,   0,   0,  48,  49,  51,  48,  16,   0,   2,   0,  31,   0
                      :   0,   0, 222,   0,   0,   0,   0,  16,   2,   0,   7,   0,   0,   0,  10,   1
                      :   0,   0,   1,  16,   3,   0,   1,   0,   0,   0,   3,   0,   0,   0,   2,  16
                      :   3,   0,   1,   0,   0,   0,   0,   0,   0,   0,  16,  16,   3,   0,   1,   0
                      :   0,   0,   2,   0,   0,   0,  17,  16,  10,   0,   1,   0,   0,   0,  18,   1
                      :   0,   0,  32,  16,   3,   0,   1,   0,   0,   0,   0,   0,   0,   0,  33,  16
                      :   3,   0,   1,   0,   0,   0,   0,   0,   0,   0,  48,  16,   3,   0,   1,   0
                      :   0,   0,   0,   0,   0,   0,  49,  16,   3,   0,   1,   0,   0,   0,   0,   0
                      :   0,   0,   0,  17,   3,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,  18
                      :   3,   0,   1,   0,   0,   0,   0,   0,   0,   0,   1,  19,   3,   0,   1,   0
                      :   0,   0,   0,   0,   0,   0,   2,  19,   3,   0,   1,   0,   0,   0,   0,   0
                      :   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0
                      :   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  52,  56
                      :  51,  49,  51,  52,  51,  54,  52,  49,  50,  48,  48,  57,  48,  50,  49,  48
                      :  66,  57,  50,  53,  57,  83,  74,  48,  49,  57,  56,  53,   0,   0,   0,   0
                      :   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  78,  79,  82,  77,  65,  76
                      :  32,   0,   0,   0,   0,   0, 100,   0,   0,   0
      title           : FUJIFILM AVI STREAM 0100
    Stream #0:1: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 11024 Hz, mono, u8, 88 kb/s
Please use -profile:a or -profile:v, -profile is ambiguous
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (pcm_u8 (native) -> aac (native))
Press [q] to stop, [?] for help
[aac @ 0x1178ac0] Specified sample rate 11024 is not supported
Error initializing output stream 0:1 -- Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

I extracted the command that doesn't work:
```
/bin/ffmpeg \
  -probesize 1000000 \
  -f avi \
  -codec:0 mjpeg \
  -codec:1 pcm_u8 \
  -i file:"/mnt/shared-archives/memories/hllau/Birthday \
  - Dad \
  - 54th/DSCF0243.AVI" \
  -map 0:0 \
  -map 0:1 \
  -map \
  -0:s \
  -c:v:0 libx264 \
  -pix_fmt yuv420p \
  -maxrate 3911808 \
  -bufsize 7823616 \
  -preset veryfast \
  -profile high \
  -level 4.1 \
  -crf 23 \
  -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none \
  -force_key_frames "expr:gte(t,n_forced*5)" \
  -vsync \
  -1 \
  -map_metadata \
  -1 \
  -map_chapters \
  -1 \
  -threads 0 \
  -codec:a:0 aac \
  -disposition:a:0 default \
  -ac:a:0 1 \
  -ab:a:0 88192 \
  -ar:a:0 11024 \
  -y "/config/sync/17/17/e13c12ff-8de3-4fb6-b5db-f43870904172.mkv"
```

And command that works:
```
/bin/ffmpeg \
  -probesize 1000000 \
  -f avi \
  -codec:0 mjpeg \
  -codec:1 pcm_u8 \
  -i file:"/mnt/shared-archives/memories/hllau/Birthday \
  - Dad \
  - 54th/DSCF0243.AVI" \
  -map 0:0 \
  -map 0:1 \
  -map \
  -0:s \
  -c:v:0 libx264 \
  -pix_fmt yuv420p \
  -maxrate 9276099 \
  -bufsize 18552198 \
  -preset veryfast \
  -profile high \
  -level 4.1 \
  -crf 23 \
  -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none \
  -force_key_frames "expr:if(isnan(prev_forced_t),eq(t,t),gte(t,prev_forced_t+3))" \
  -copyts \
  -vsync \
  -1 \
  -map_metadata \
  -1 \
  -map_chapters \
  -1 \
  -threads 0 \
  -codec:a:0 aac \
  -disposition:a:0 default \
  -ac:a:0 1 \
  -ab:a:0 88192 \
  -f segment \
  -max_delay 5000000 \
  -avoid_negative_ts disabled \
  -start_at_zero \
  -segment_time 3 \
  -individual_header_trailer 0 \
  -segment_format mpegts \
  -segment_list_type m3u8 \
  -segment_start_number 0 \
  -segment_list "/config/transcoding-temp/abd00b66269e04343d8a8fc2a62e73bb.m3u8" \
  -y "/config/transcoding-temp/abd00b66269e04343d8a8fc2a62e73bb%d.ts"
```

**Comment by LukePulverenti** [comment]
Can you provide a copy of the avi file for testing? thanks !

**Comment by hllau** [comment]
Yes, @LukePulverenti. here you are. Thank you.
https://public.hllau.com/20190210-github-embyserver-issue/DSCF0243.AVI
Please let me know when it's been downloaded. I would like to remove it publicly afterwards.

**Comment by LukePulverenti** [comment]
Got it, thanks.

**Comment by LukePulverenti** [comment]
Resolved for next release, thanks !

**Comment by hllau** [comment]
Thank you very much Luke.

One thing that would be great is to provide an error message on the client side too, Right now, the client just does nothing when an error occurs, leaving users guessing what’s happening and pondering why the files were not downloaded.

On 11 Feb 2019, at 04:08, Luke <notifications@github.com> wrote:

Closed #3524.

**Comment by hllau** [comment]
I have updated version to 4.0.2.0 and problem persists. Is 4.0.2.0 the "next release" you were talking about please? @LukePulverenti  Thank you.
