### ISSUE TITLE
Continuous playback stops when the transcode position hits end of video

### ISSUE THREAD

**Issue by solarchemist** [MediaBrowser/Emby#3529]
When playing content that requires transcoding by the server I have observed that playback stops when the transcode position hits the end of the file. This was not the case with earlier Emby server versions (I'm not sure which version introduced this issue, but probably >4.0)..

Here's the server and client spec
Emby Server 4.0.1.0 on Ubuntu Server 16.04.5, with ffmpeg version 3.3.3.
Client: I've observed this playback issue with the Emby webapp in both Chromium 72.0.3626.96 and Google Chrome 72.0.3626.119  (latest stable) on Debian Stretch 9.8. 

The playback suddenly halts around 2:40 min before the end of the episode, precisely corresponding to when the Emby server dashboard indicates that transcoding has reached the end of the file.
Trying to click pause/play to restart the playback only resets the seeker to 0:00 but fails to resume playback at all. Only recourse appears to be back out into the Emby menu, play the same episode again and move the seeker manually. Furthermore it seems that only *continuous playback* is affected by this issue; playing back the last few minutes by moving the seeker manually works fine, also if I move the seeker around during playback of another episode the halt does not occur.

This is what the Emby log show (with debug mode enabled):
```
2019-02-19 13:43:47.949 Info App: CodecValidation: vaapi will throw an error with mpeg4 input
2019-02-19 13:43:47.949 Info App: CodecValidation: FindVideoEncoder - Encoder does not match
2019-02-19 13:43:47.956 Info App: ProcessRun 'StreamTranscode 25cd66' Execute: /opt/emby-server/bin/ffmpeg -ss 00:46:00.000  -f avi -i file:"/media/tv/ER (1994)/Season 01/er.01x19.love's.labour.lost.dvdrip.xvid-mp3.dvd-r.avi" -threads 0 -map 0:0 -map 0:1 -map -0:s -c:v:0 libx264 -pix_fmt yuv420p  -maxrate 2787432 -bufsize 5574864 -preset veryfast -profile high -level 4.1 -crf 23 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:if(isnan(prev_forced_t),eq(t,t),gte(t,prev_forced_t+3))" -copyts -vsync -1 -codec:a:0 copy -disposition:a:0 default -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -start_at_zero -segment_time 3 -segment_time_delta -2760 -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 920 -segment_list "/var/lib/emby/transcoding-temp/5fa6b130cf540924a9eb9687309476fc.m3u8" -y "/var/lib/emby/transcoding-temp/5fa6b130cf540924a9eb9687309476fc%d.ts"
2019-02-19 13:43:48.005 Info App: ProcessRun 'StreamTranscode 25cd66' Started.
2019-02-19 13:43:48.099 Info App: ProcessRun 'StreamTranscode 25cd66' Process exited with code 0
2019-02-19 13:43:48.109 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.0.1.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.4.0.139
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 8
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.Exception: System.Exception: Error starting ffmpeg
	   at Emby.Server.MediaEncoding.Api.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, EncodingOptions encodingOptions, CancellationTokenSource cancellationTokenSource, Boolean acquireResources)
	   at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String playlistId, String segmentId, Int32 subtitleStreamIndex)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
	Source: Emby.Server.MediaEncoding
	TargetSite: Void MoveNext()
	   at Emby.Server.MediaEncoding.Api.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, EncodingOptions encodingOptions, CancellationTokenSource cancellationTokenSource, Boolean acquireResources)
	   at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String playlistId, String segmentId, Int32 subtitleStreamIndex)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

and the ffmpeg log (not the same timestamps, but it's the same otherwise):
```
2019-02-22 14:20:33.907
Application version: 4.0.1.0
http://emby.mydomain.com:8096/videos/3472/hls1/main/901.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvNzEuMC4zNTc4LjgwIFNhZmFyaS81MzcuMzZ8MTU0OTgyOTc0MDYwMg11&MediaSourceId=e699cd8ed5fac201f0aa4edc48bb1c38&VideoCodec=h264&AudioCodec=mp3,aac&VideoBitrate=139808000&AudioBitrate=192000&PlaySessionId=9b9c1683547640e99ac59682066897d1&api_key=45f7cfc64feb40199d5deecebc772fdb&AudioStreamIndex=1&SubtitleStreamIndex=2&SubtitleMethod=Hls&TranscodingMaxAudioChannels=2&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline,high10&h264-level=51&TranscodeReasons=ContainerNotSupported

{"Protocol":"File","Id":"e699cd8ed5fac201f0aa4edc48bb1c38","Path":"/media/tv/ER (1994)/Season 02/er.02x18.a.shift.in.the.night.dvdrip.xvid-ac3.avi","Type":"Default","Container":"avi","Size":0,"Name":"er.02x18.a.shift.in.the.night.dvdrip.xvid-ac3","IsRemote":false,"RunTimeTicks":27032449024,"ReadAtNativeFramerate":false,"DiscardCorruptPts":false,"FillWallClockDts":false,"IgnoreDts":false,"IgnoreIndex":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"MediaStreams":[{"Codec":"mpeg4","CodecTag":"XVID","TimeBase":"125/2997","CodecTimeBase":"125/2997","VideoRange":"SDR","DisplayTitle":"SD MPEG4","IsInterlaced":false,"BitRate":880267,"RefFrames":1,"IsDefault":false,"IsForced":false,"Height":384,"Width":512,"AverageFrameRate":23.976,"RealFrameRate":23.976,"Type":"Video","AspectRatio":"4:3","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":-99},{"Codec":"ac3","TimeBase":"1/24000","CodecTimeBase":"1/48000","DisplayTitle":"Dolby Digital stereo","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":192000,"Channels":2,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"srt","Language":"eng","DisplayTitle":"Eng","IsInterlaced":false,"IsDefault":false,"IsForced":false,"Type":"Subtitle","Index":2,"IsExternal":true,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/media/tv/ER (1994)/Season 02/er.02x18.a.shift.in.the.night.dvdrip.xvid-ac3.en.srt"}],"Formats":[],"Bitrate":1078985,"RequiredHttpHeaders":{}}

User policy for <username>: EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True

Affected codecs:
>>>>>>  VAAPI Intel Corporation Device 22813 - H.264 (AVC)
        Adapter #0: 'Intel Corporation Device 22813' Id:22813 (Driver: Intel i965 driver for Intel(R) Kaby Lake - 2.2.0, Vendor: Intel Corporation)
        Frame Sizes: 32x32...4096x4096
        Color Formats: NV12, P010LE
        Profiles: Constrained Baseline Profile (Level 6), Main Profile (Level 6), High Profile (Level 6)

>>>>>>  libx264 Software Encoder
        Color Formats: YUV420P, YUVJ420P, YUV422P, YUVJ422P, YUV444P, YUVJ444P, NV12, NV16, NV21, YUV420P10LE, YUV422P10LE, YUV444P10LE, NV20LE
        Profiles: Baseline Profile (Level 6.2), Main Profile (Level 6.2), High Profile (Level 6.2), High 10 Profile (Level 6.2), High 4:2:2 Profile (Level 6.2), High 4:4:4 Profile (Level 6.2)

>>>>>>  FindVideoDecoder - MediaType: mpeg4, Mode: 1
Info    FindVideoDecoder - Checking: 'Automatic software decoder' (Priority: 0)
Info    FindVideoDecoder - Check successful - selecting 'Automatic software decoder'

>>>>>>  FindVideoEncoder - Media: h264, UseHardwareCodecs: True, Mode: 1
Info    FindVideoEncoder - Checking: 'VAAPI Intel Corporation Device 22813 - H.264 (AVC)' (Priority: 60)
NoMatch vaapi will throw an error with mpeg4 input
NoMatch FindVideoEncoder - Encoder does not match
Info    FindVideoEncoder - Checking: 'libx264 Software Encoder' (Priority: 0)
Info    Encoder supports input stream
Info    FindVideoEncoder - Check successful - selecting 'libx264 Software Encoder'

/opt/emby-server/bin/ffmpeg -ss 00:45:03.000  -f avi -i file:"/media/tv/ER (1994)/Season 02/er.02x18.a.shift.in.the.night.dvdrip.xvid-ac3.avi" -threads 0 -map 0:0 -map 0:1 -map -0:s -c:v:0 libx264 -pix_fmt yuv420p  -maxrate 2640801 -bufsize 5281602 -preset veryfast -profile high -level 4.1 -crf 23 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:if(isnan(prev_forced_t),eq(t,t),gte(t,prev_forced_t+3))" -copyts -vsync -1 -codec:a:0 libmp3lame -disposition:a:0 default -ac:a:0 2 -ab:a:0 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -start_at_zero -segment_time 3 -segment_time_delta -2703 -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 901 -segment_list "/var/lib/emby/transcoding-temp/671a010fe4a775b38b18f544e61b5f38.m3u8" -y "/var/lib/emby/transcoding-temp/671a010fe4a775b38b18f544e61b5f38%d.ts"
ffmpeg version 4.0.2-emby_2018_12_09 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (crosstool-NG crosstool-ng-1.23.0)
  configuration: --cc=x86_64-pc-linux-gnu-gcc --arch=x86_64 --prefix=/home/embybuilder/Buildbot/x64/ffmpeg-x64/staging --pkg-config=pkg-config --disable-doc --disable-ffplay --disable-vdpau --disable-xlib --enable-fontconfig --enable-gnutls --enable-gpl --enable-iconv --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libzvbi --enable-version3 --enable-libsmbclient --enable-cuda --enable-cuvid --enable-libmfx --enable-nvenc --enable-vaapi --enable-cross-compile --cross-prefix=x86_64-pc-linux-gnu- --extra-libs='-lexpat -lfreetype -lfribidi -lfontconfig -liconv -lpng -lz -lvorbis -logg -lnettle -lhogweed -lgmp -laddns-samba4 -lasn1util-samba4 -lauthkrb5-samba4 -lCHARSET3-samba4 -lcliauth-samba4 -lcli-cldap-samba4 -lcli-ldap-common-samba4 -lcli-nbt-samba4 -lcli-smb-common-samba4 -lcom_err -lcommon-auth-samba4 -ldbwrap-samba4 -ldcerpc-binding -ldcerpc-samba-samba4 -ldl -lflag-mapping-samba4 -lgenrand-samba4 -lgensec-samba4 -lgse-samba4 -lgssapi_krb5 -llibcli-lsa3-samba4 -llibsmb-samba4 -linterfaces-samba4 -liov-buf-samba4 -lk5crypto -lkrb5 -lkrb5samba-samba4 -lkrb5support -lldb -lldbsamba-samba4 -lmessages-dgm-samba4 -lmessages-util-samba4 -lmsghdr-samba4 -lmsrpc3-samba4 -lndr -lndr-krb5pac -lndr-nbt -lndr-samba-samba4 -lndr-standard -lreplace-samba4 -lsamba-cluster-support-samba4 -lsamba-credentials -lsamba-debug-samba4 -lsamba-errors -lsamba-hostconfig -lsamba-modules-samba4 -lsamba-security-samba4 -lsamba-sockets-samba4 -lsamba-util -lsamba3-util-samba4 -lsamdb -lsamdb-common-samba4 -lsecrets3-samba4 -lserver-id-db-samba4 -lserver-role-samba4 -lsmbconf -lsmbd-shim-samba4 -lsmb-transport-samba4 -lsocket-blocking-samba4 -lsys-rw-samba4 -ltalloc -ltalloc-report-samba4 -ltdb -ltdb-wrap-samba4 -ltevent -ltevent-util -ltime-basic-samba4 -lutil-cmdline-samba4 -lutil-reg-samba4 -lutil-setid-samba4 -lutil-tdb-samba4 -luuid -lwbclient -lwinbind-client-samba4 -ldrm' --target-os=linux --enable-shared --disable-static
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[mpeg4 @ 0x20a8cc0] Failed to parse extradata
Input #0, avi, from 'file:/media/tv/ER (1994)/Season 02/er.02x18.a.shift.in.the.night.dvdrip.xvid-ac3.avi':
  Metadata:
    encoder         : Nandub v1.0rc2
  Duration: 00:45:03.24, start: 0.000000, bitrate: 1078 kb/s
    Stream #0:0: Video: mpeg4 (XVID / 0x44495658), yuv420p, 512x384 [SAR 1:1 DAR 4:3], 880 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
    Stream #0:1: Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 192 kb/s
Please use -profile:a or -profile:v, -profile is ambiguous
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (ac3 (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[NULL @ 0x20a8cc0] Failed to parse extradata
[libx264 @ 0x20e9c80] using SAR=1/1
[libx264 @ 0x20e9c80] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x20e9c80] profile Main, level 4.1
[libx264 @ 0x20e9c80] 264 - core 152 r2854 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x1:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=4 chroma_me=0 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=23 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=2640 vbv_bufsize=5281 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00
[segment @ 0x20e7f00] Opening '/var/lib/emby/transcoding-temp/671a010fe4a775b38b18f544e61b5f38901.ts' for writing
Output #0, segment, to '/var/lib/emby/transcoding-temp/671a010fe4a775b38b18f544e61b5f38%d.ts':
  Metadata:
    encoder         : Lavf58.12.100
    Stream #0:0: Video: h264 (libx264), yuv420p, 512x384 [SAR 1:1 DAR 4:3], q=-1--1, 23.98 fps, 90k tbn, 23.98 tbc
    Metadata:
      encoder         : Lavc58.18.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 2640000/0/0 buffer size: 5281000 vbv_delay: -1

    Stream #0:1: Audio: mp3 (libmp3lame), 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      encoder         : Lavc58.18.100 libmp3lame
[ac3 @ 0x20ae240] incomplete frame
[segment @ 0x20e7f00] Opening '/var/lib/emby/transcoding-temp/671a010fe4a775b38b18f544e61b5f38.m3u8.tmp' for writing
frame=    6 fps=0.0 q=-1.0 Lsize=N/A time=00:45:03.24 bitrate=N/A speed=1.33e+05x    
video:2kB audio:6kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[libx264 @ 0x20e9c80] frame I:1     Avg QP:13.75  size:  1028
[libx264 @ 0x20e9c80] frame P:2     Avg QP:14.65  size:   196
[libx264 @ 0x20e9c80] frame B:3     Avg QP:14.31  size:    84
[libx264 @ 0x20e9c80] consecutive B-frames: 33.3%  0.0%  0.0% 66.7%
[libx264 @ 0x20e9c80] mb I  I16..4: 91.7%  0.0%  8.3%
[libx264 @ 0x20e9c80] mb P  I16..4:  4.3%  0.0%  0.0%  P16..4:  6.6%  0.0%  0.0%  0.0%  0.0%    skip:89.1%
[libx264 @ 0x20e9c80] mb B  I16..4:  0.1%  0.0%  0.0%  B16..8:  5.3%  0.0%  0.0%  direct: 0.8%  skip:93.8%  L0:69.4% L1:30.6% BI: 0.0%
[libx264 @ 0x20e9c80] coded y,uvDC,uvAC intra: 2.3% 0.0% 0.0% inter: 0.7% 0.0% 0.0%
[libx264 @ 0x20e9c80] i16 v,h,dc,p: 69% 23%  4%  3%
[libx264 @ 0x20e9c80] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 22% 39%  2%  2%  1%  2%  1%  1%
[libx264 @ 0x20e9c80] i8c dc,h,v,p: 100%  0%  0%  0%
[libx264 @ 0x20e9c80] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x20e9c80] kb/s:53.45
```
Anyone else observing this when transcoding? Should I perhaps try to upgrade the ffmpeg on Ubuntu 16.04? Or is Emby using its own ffmpeg anyway?

**Comment by LukePulverenti** [comment]
Hi, Emby is using it's own ffmpeg. Have you updated to Emby Server 4.0.2?

**Comment by solarchemist** [comment]
No, I must have missed that it was released. I'll go ahead and update then.

**Comment by solarchemist** [comment]
Upgraded Emby server to 4.0.2 a couple of days ago. Everything else the same.
I'm still observing that playback halts for these transcoding jobs once the transcode position reaches end-of-file. Here's the Emby logfile immediately after playback stops (same as before the upgrade as far as I can tell):
```
2019-02-26 22:52:05.512 Debug App: Starting transcoding because currentTranscodingIndex=null
2019-02-26 22:52:05.512 Debug App: KillTranscodingJob - JobId 6820a228-02a2-4227-9523-ae2a471409d1 PlaySessionId c8a68b66cb4a4abea202fa259a428773. Killing transcoding
2019-02-26 22:52:05.513 Debug App: CodecValidation: FindVideoDecoder - MediaType: mpeg4, Mode: 1
2019-02-26 22:52:05.513 Debug App: CodecValidation: FindVideoDecoder - Checking: 'Automatic software decoder' (Priority: 0)
2019-02-26 22:52:05.513 Debug App: CodecValidation: FindVideoDecoder - Check successful - selecting 'Automatic software decoder'
2019-02-26 22:52:05.513 Debug App: CodecValidation: FindVideoEncoder - Media: h264, UseHardwareCodecs: True, Mode: 1
2019-02-26 22:52:05.513 Debug App: CodecValidation: FindVideoEncoder - Checking: 'VAAPI Intel Corporation Device 22813 - H.264 (AVC)' (Priority: 60)
2019-02-26 22:52:05.513 Info App: CodecValidation: vaapi will throw an error with mpeg4 input
2019-02-26 22:52:05.513 Info App: CodecValidation: FindVideoEncoder - Encoder does not match
2019-02-26 22:52:05.513 Debug App: CodecValidation: FindVideoEncoder - Checking: 'libx264 Software Encoder' (Priority: 0)
2019-02-26 22:52:05.513 Debug App: CodecValidation: Encoder supports input stream
2019-02-26 22:52:05.513 Debug App: CodecValidation: FindVideoEncoder - Check successful - selecting 'libx264 Software Encoder'
2019-02-26 22:52:05.516 Debug App: ThrottleByStreamBufferSize: Initialize - TargetBufferSize: 120s - Hysteresis: 5s
2019-02-26 22:52:05.516 Info App: ProcessRun 'StreamTranscode 7046b7' Execute: /opt/emby-server/bin/ffmpeg -ss 00:44:54.000  -f avi -i file:"/media/bay/tv/ER (1994)/Season 04/er.04x14.family.practice.dvdrip.xvid-mp3.sfm.avi" -threads 0 -map 0:0 -map 0:1 -map -0:s -c:v:0 libx264 -pix_fmt yuv420p  -maxrate 2652435 -bufsize 5304870 -preset veryfast -profile high -level 4.1 -crf 23 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:if(isnan(prev_forced_t),eq(t,t),gte(t,prev_forced_t+3))" -copyts -vsync -1 -codec:a:0 libmp3lame -disposition:a:0 default -ac:a:0 2 -ab:a:0 192000  -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -start_at_zero -segment_time 3 -segment_time_delta -2694 -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 898 -segment_list "/var/lib/emby/transcoding-temp/9d490e2bf2e0e130a740d93404fd97ef.m3u8" -y "/var/lib/emby/transcoding-temp/9d490e2bf2e0e130a740d93404fd97ef%d.ts"
2019-02-26 22:52:05.528 Info App: ProcessRun 'StreamTranscode 7046b7' Started.
2019-02-26 22:52:05.604 Info App: ProcessRun 'StreamTranscode 7046b7' Process exited with code 0
2019-02-26 22:52:05.632 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 4.0.2.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.4.0.139
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 8
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	System.Exception: System.Exception: Error starting ffmpeg
	   at Emby.Server.MediaEncoding.Api.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, EncodingOptions encodingOptions, CancellationTokenSource cancellationTokenSource, Boolean acquireResources)
	   at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String playlistId, String segmentId, Int32 subtitleStreamIndex)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
	Source: Emby.Server.MediaEncoding
	TargetSite: Void MoveNext()
	   at Emby.Server.MediaEncoding.Api.BaseStreamingService.StartFfMpeg(StreamState state, String outputPath, EncodingOptions encodingOptions, CancellationTokenSource cancellationTokenSource, Boolean acquireResources)
	   at Emby.Server.MediaEncoding.Api.Hls.DynamicHlsService.GetDynamicSegment(StreamRequest request, String playlistId, String segmentId, Int32 subtitleStreamIndex)
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
	
2019-02-26 22:52:05.632 Info HttpServer: HTTP Response 500 to 192.168.1.1. Time: 121ms. http://emby.mydomain.com:8096/videos/3524/hls1/main/898.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvNzEuMC4zNTc4LjgwIFNhZmFyaS81MzcuMzZ8MTU0OTgyOTc0MDYwMg11&MediaSourceId=728875dcac4626504a3c910cceb667ec&VideoCodec=h264&AudioCodec=mp3,aac&VideoBitrate=139808000&AudioBitrate=192000&PlaySessionId=c8a68b66cb4a4abea202fa259a428773&AudioStreamIndex=1&SubtitleStreamIndex=2&SubtitleMethod=Hls&TranscodingMaxAudioChannels=2&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline,high10&h264-level=51&TranscodeReasons=ContainerNotSupported
2019-02-26 22:52:20.185 Info HttpServer: HTTP POST http://emby.mydomain.com:8096/Sessions/Playing/Progress. UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
```

**Comment by LukePulverenti** [comment]
There's a good chance this is resolved in Emby Server 4.1+. If you'd like to try it now you can install the beta package. Thanks.

**Comment by LukePulverenti** [comment]
Hi there, were you able to try this with 4.1.1? Thanks.

**Comment by solarchemist** [comment]
Hi, thanks for following up. I'm afraid the same behaviour still occurs on Emby 4.1.1.0. 

I think the issue is confined to certain types of video files. I have noticed that not all playback that requires server transcoding suffers this issue. I'm not very familiar with codecs and such, but I assume that it's only some specific kind that causes this issue. This was the case before the latest Emby update too.

The same episodes that cutoff before still cutoff now. I have tried one thing since updating to 4.1.1 - since my Emby server had hardware acceleration enabled, I disabled it, restarted the server and replayed some episodes. But the change seemingly had no effect. I have since re-enabled hardware acceleration again, in case it does some good for other content.

Please note that this issue is not a dealbreaker for me - a very small minority of content on my server is affected. I have also transcoded some episodes and saved to disk to avoid on-the-fly transcoding and this issue in the future. So if you want to close, I wouldn't object. I only hope this report might perhaps aid some other Emby admin down the road.

But I'd be happy to keep digging :-) If you would like more details/logs, I can probably get back to you during the weekend. Please note that so far testing is rather time-consuming, since the the episode needs to play to the end before the issue manifests (or not) and fiddling with the seeker during playback appears to mask the effect.

**Comment by LukePulverenti** [comment]
Hi there, please try Emby Server 4.2 and let me know how that compares. Thanks.

**Comment by solarchemist** [comment]
Hi @LukePulverenti. Have been running v4.2 for over a week now, and I cannot reproduce this issue any more. Seems that you fixed it!
