### ISSUE TITLE
Beta docker container can't start `Cannot get required symbol ENGINE_by_id from libssl`

### ISSUE THREAD

**Issue by troykelly** [MediaBrowser/Emby#3822]
# Issue
The beta docker container that has been recently updated will now not start with this error:

```text
2024-02-27T01:56:28.337716379Z [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
2024-02-27T01:56:28.370666970Z [s6-init] ensuring user provided files have correct perms...exited 0.
2024-02-27T01:56:28.371857341Z [fix-attrs.d] applying ownership & permissions fixes...
2024-02-27T01:56:28.373085133Z [fix-attrs.d] done.
2024-02-27T01:56:28.373953270Z [cont-init.d] executing container initialization scripts...
2024-02-27T01:56:28.375036020Z [cont-init.d] done.
2024-02-27T01:56:28.375875765Z [services.d] starting services
2024-02-27T01:56:28.381872465Z [services.d] done.
2024-02-27T01:56:28.432958639Z Cannot get required symbol ENGINE_by_id from libssl
2024-02-27T01:56:28.534583532Z Aborted (core dumped)
2024-02-27T01:56:28.540165643Z [cont-finish.d] executing container finish scripts...
2024-02-27T01:56:28.541137501Z [cont-finish.d] done.
2024-02-27T01:56:28.541510223Z [s6-finish] waiting for services.
2024-02-27T01:56:28.745528331Z [s6-finish] sending all processes the TERM signal.
2024-02-27T01:56:28.746150803Z Hangup
```

# Environment
emby/embyserver@sha256:1f3f0e5bfd393b001a8c357fd402f5b83f3b99be961e17422d3f7a7856dee1e5
Ubuntu 23.10
Docker version 25.0.3, build 4debf41
NVIDIA Driver Version: 545.23.08
CUDA Version: 12.3

# Notes

I can't switch back to "latest" because of the lack of compatibility between beta and latest, but latest does appear to at least try and start, throwing a SQLite exception.

**Comment by LukePulverenti** [comment]
Hi, yes please follow along here: https://emby.media/community/index.php?/topic/126711-4906-fails-cannot-get-required-symbol-engine_by_id-from-libssl/
Thanks.

**Comment by troykelly** [comment]
For those who don't want to have to create an account in a Forum to track a bug with Emby - here is a brief update:
 - Some Linux users are reporting success with [4.9.0.7](https://hub.docker.com/layers/emby/embyserver/4.9.0.7/images/sha256-c2ef19dc8c0db60be67ece256c94c3da3079e731ac47749a177b3c7deaf51564?context=explore) 
 - There is also a [4.9.0.8](https://hub.docker.com/layers/emby/embyserver/4.9.0.8/images/sha256-15b582ec706fdec5ea275ef1d5120d408793c408aa42dc26b79f518f916de336?context=explore) version in Docker Hub, but no information from Emby staff as to what this version resolves (if anything?)
 - Recent [Emby releases](https://github.com/MediaBrowser/Emby.Releases/releases) have no mention of the libssl bug at all
 
There is a reticence of those in the forum to test though, as for many this involves rebuilding - still waiting for any comment from Emby beyond acknowledging the issue several days ago.

**Comment by LukePulverenti** [comment]
HI, it is resolved in 4.9.0.8. Thanks.

**Comment by troykelly** [comment]
Thanks @LukePulverenti - I'm still not seeing that in the release notes though?

**Comment by LukePulverenti** [comment]
Sorry, my mistake. It's been added. Thanks.

**Comment by Saberian1992** [comment]
@[](https://app.gmt.io/nft/view/9682b8de-27aa-4329-9300-b8ee6085d112)
